version: "3"

services:

  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/cache/:/etc/nginx/cache
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443
    networks:
      - "api"
      - "inventory-domain"
    depends_on:
      - "inventory-service"
    restart: "on-failure"

  client-web:
    image: "client-web"
    build:
      context: "client-web"
    networks:
      - "frontend"
      - "api"
    ports:
      - "3000:3000"
    depends_on:
      - "nginx"
    restart: "on-failure"

  purchaseorders-service:
    hostname: "purchaseorders"
    image: "purchaseorders-service"
    build:
      context: "microservices/purchaseorders-service"
    networks:
      - "purchaseorders-domain"
      - "database"
    expose:
      - "3000"
    depends_on:
      - "database"

  inventory-service:
    hostname: "inventory"
    image: "inventory-service"
    build:
      context: "microservices/inventory-service"
    networks:
      - "inventory-domain"
      - "database"
    expose:
      - "3000"
    depends_on:
      - "database"

  swagger-ui:
    image: "swaggerapi/swagger-ui:v3.25.0"
    networks:
      - "frontend"
    ports:
      - "8080:8080"
    volumes:
      - "./docs/openapi-spec.yaml:/usr/share/spec/openapi-spec.yaml"
    environment:
      SWAGGER_JSON: "/usr/share/spec/openapi-spec.yaml"
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "localhost:8080 -q -O - > /dev/null 2>&1"
        ]
      interval: 30s
      timeout: 10s
      retries: 5

  database:
    image: "postgres:12.1-alpine"
    networks:
      - "database"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "isamyresfashion"
      POSTGRES_PASSWORD: "7is0122010"
    healthcheck:
      test: [ "CMD-SHELL", "su -c 'pg_isready -U postgres' postgres" ]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: "on-failure"
    
networks:
  frontend: null
  api: null
  inventory-domain: null
  purchaseorders-domain: null
  database: null
